### PR TITLE
Added support for macOS

### LINKED ISSUE #143: Add support for OSX
### Expected Behavior

make it work lol

### Current Behavior

It does not build on systems without Xcode.

### Steps to Reproduce Behavior

How can we reproduce this?

### Logs

Are there any logs?

### System information

* PyDP version: 0.1.1
* Python version: 3+
* Bazel version:
* Operating System: OSX

### PR DESCRIPTION
**Pull request by madhavajay**
- Removed third_party folder
- Updated Bazel WORKSPACE
- Fixed paths in example/carrots.py
- Added Pipfile for virtualenv
- Added build_macos.sh script

Fixes #143 

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Yes the carrots demo runs.

### CODE REVIEW

**Review by iamtrask — DISMISSED** [review]
Looks great to me! But I’d wait until another review before merging.

**Comment by madhavajay** [comment]
Hrm... looks like i have broken things.
I tried to add an update but because i'm no longer authorized to push here I need to push to my fork, which auto updates this PR somehow... So my last commit has leapt forward to today which is weird.

I actually was trying to get this Commit in.
https://github.com/madhavajay/PyDP/commit/6d2b313b4073bd0653667f3a5f9bf82cc8cbf7e0

I made the mistake of thinking maybe I should try the GitHub Desktop app and I think that just made it worse with some weird merge strategy auto stuff... I should have manually force pushed this branch up onto my fork first. Now I am hesitant to do anything in case I make it worse. If someone wants to make the change above I linked to, I believe it fixes an error in the xargs command on linux CI.
https://github.com/OpenMined/PyDP/runs/718826904?check_suite_focus=true
```
INFO: Build completed successfully, 637 total actions
INFO: Build completed successfully, 637 total actions
rm: missing operand
Try 'rm --help' for more information.
``` 

But this needs to be confirmed, although its not really needed on CI since its a clean environment which would explain why this didn't get noticed. We could possibly put something like:
```bash
set -o pipefail
```

That way any error will cause the test to fail so we don't miss silent errors.

**Comment by madhavajay** [comment]
Other than that update, I think the PR is good! 👍

**Comment by madhavajay** [comment]
Also how do we feel about Squash and Force Push on branches like these before Merging the PR?

**Comment by chinmayshah99** [comment]
> I actually was trying to get this Commit in.
> madhavajay@6d2b313

Manually adding this.

**Comment by chinmayshah99** [comment]
@madhavajay 
When I add make changes in my local machine as mentioned in madhavajay/PyDP@6d2b313:
```
INFO: Build completed successfully, 1 total action
xargs: WARNING: a NUL character occurred in the input.  It cannot be passed through in the argument list.  Did you mean to use the --null option?

```

**Review by chinmayshah99 — APPROVED** [review]

**Comment by chinmayshah99** [comment]
> Also how do we feel about Squash and Force Push on branches like these before Merging the PR?

If the code does one functionality then yes.
In this case, this repo had a couple of things that were fixed among like 20+ files. So it made more sense to merge commit. 
In the pypi #136 , we did squash commit.

**Comment by madhavajay** [comment]
Regarding the xargs error, its always a challenge to get bash scripts to work perfectly on linux and mac, but I should have actually tested it on a local docker container first. Sorry for that, this works and has been tested on both platforms:
```bash
find ./ -name pydp.so -print0 | xargs -0 -I {} rm {}
```

For the commits I just mean there are a lot of "fixing errors" commits in this PR which could be squashed into a single commit. Its just a style preference and doesn't really matter but makes reviewing the whole PR in the longer history of the repo a little easier.

**Comment by chinmayshah99** [comment]
This looks great. Can you make a PR if you don't mind?

**Pull request merged**
