### PR TITLE
Fix build bug in docs build

### PR DESCRIPTION
**Pull request by BrendanSchell**
## Description
Fix for #303 according to benj's suggestion. This was a prerequisite for testing the issue I was assigned #292.

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
`make test`

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by BrendanSchell** [comment]
@chinmayshah99

**Review by chinmayshah99 — DISMISSED** [review]
LGTM! I'll let @alejandrosame weigh on this.

**Comment by chinmayshah99** [comment]
Does this still generate coverage results?

**Comment by BrendanSchell** [comment]
> Does this still generate coverage results?

@chinmayshah99 it actually wasn't, so that's a good catch! Reverted back to the coverage command (instead of build command) and now it does.

**Comment by alejandrosame** [comment]
LGTM!

**Review by alejandrosame — APPROVED** [review]

**Review by chinmayshah99 — APPROVED** [review]

**Pull request merged**
