### PR TITLE
Added README.md file for restaurant_demo

### PR DESCRIPTION
**Pull request by Rajatendu1**
This file contains a short description of the working of the restaurant.py file.

## Description
Added description for restaurant.py .

## Affected Dependencies
None

## How has this been tested?
Added a description for a file, no testing required.
## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Review by 8bitmp3 — CHANGES_REQUESTED** [review]
Hi @Rajatendu1 Thanks for this. Can you please address the following:
- Use spaces after commas
- Apply/don't apply capitalization for variables. For placeholders, it may be best use non-code plain Enlgish descriptions
- Use code font (e.g. `codeFont`) for variable names
- Use American English ("...sation" -> "...zation")
- Use second person ("you" or "the reader" <- "we")
- Double check the grammar/syntax by running the text through a free Google Doc -> then use their free grammar/syntax checking tool
- Add links and/or short explanations to PyDP/diff privacy-specific terms (e.g. Laplacian, `BoundedSum`), also use normal terms instead of variable names, if you can - this doc should be the main point of reference to understand what's going on
- Format headings and titles properly (check out https://developers.google.com/style/headings?hl=en) - e.g. `# Heading 1 .. ## Heading 2`
- Maybe add requirements ("The reader should be familiar with X... Python/etc etc")

Glance through the Google style doc that many folks use to write better READMEs and docs: https://developers.google.com/style

It can make a huge difference to the readers who stand to benefit from this awesome demo 👍 

Cheers

**Comment by 8bitmp3** [comment]
Found this: https://x-team.com/blog/how-to-write-a-great-readme/ - it may be helpful

**Comment by 8bitmp3** [comment]
https://x-team.com/blog/how-to-write-a-great-readme/ - "How to write a great README" - it may be helpful

What to Include in Your README

> Here are some of the essential things to include when you're writing your README. We'll assume that you're familiar with markdown to organize your file and make it look good.
> 
> - Title (can be text or an image)
> - Introduction (what it's about & why you wrote it)
> - How to install
> - How to use
> - Technologies used (libraries & versions, helps recruiters)
> - Acknowledgments
>
> Those are the absolute essentials. They make for a good README. If you want to write a great one, you can take it a step further and include:
> 
> - Table of contents (useful if your README is long)
> - List of features
> - Examples of use (with code or images)

**Comment by shaistha24** [comment]
Hi, @Rajatendu1 @8bitmp3 Just a suggestion. Summarizing the examples and the results should be enough. Not the procedure but what is the demo? If you get it. Like, share the scenarios. #313 

Pls use Reference Carrot Demo Readme: https://github.com/OpenMined/PyDP/tree/dev/examples/carrots_demo

**Comment by chinmayshah99** [comment]
Hi @Rajatendu1, #313 is already taken up by someone else. Would highly recommend you talk to the person already working on it and coordinate accordingly. 

While we try our maximum to duplicate such efforts, a good idea would be to take a look at the open issues and work on it accordingly.

**Pull request closed without merging**
