### PR TITLE
Single Sourcing The Package Version

### PR DESCRIPTION
**Pull request by codeboy5**
# Pull Request

## Description
Modified the `setup.py` so that version can be automatically inferred from the `pydp\init.py` file.

## Affected Dependencies
List any dependencies that are required for this change.

## Type of Change
Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation (non-breaking change which adds documentation)
- [x] Improvement (non-breaking change that improves the performance or reliability of existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I did follow the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md)
- [x] I did follow the [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have added tests for my changes

## Additional Context
Please also include relevant motivation and context.

### CODE REVIEW

**Comment by codeboy5** [comment]
> # Pull Request
> ## Description
> Modified the `setup.py` so that version can be automatically inferred from the `pydp\init.py` file.
> 
> ## Affected Dependencies
> List any dependencies that are required for this change.
> 
> ## Type of Change
> Please mark options that are relevant.
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  Documentation (non-breaking change which adds documentation)
> * [x]  Improvement (non-breaking change that improves the performance or reliability of existing functionality)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
> ## How has this been tested?
> * Describe the tests that you ran to verify your changes.
> * Provide instructions so we can reproduce.
> * List any relevant details for your test configuration.
> 
> ## Checklist
> * [x]  I did follow the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md)
> * [x]  I did follow the [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
> * [ ]  I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
> * [ ]  I have added tests for my changes
> 
> ## Additional Context
> Please also include relevant motivation and context.

@chinmayshah99 let me know if you think this is a good addition.

**Comment by chinmayshah99** [comment]
We are already using bumpversion to change the version. So this seems to just increase the complexity. Check out `setup.cfg`

**Comment by codeboy5** [comment]
> We are already using bumpversion to change the version. So this seems to just increase the complexity. Check out `setup.cfg`

Ohh just saw that, we can close this then .

**Comment by chinmayshah99** [comment]
Just a general question, is doing this an acceptable practice?

**Comment by codeboy5** [comment]
> Just a general question, is doing this an acceptable practice?

https://packaging.python.org/guides/single-sourcing-package-version/ . Saw this in the official python packaging user guide.

**Pull request closed without merging**
