### PR TITLE
Move from tox to pytest #192

### PR DESCRIPTION
**Pull request by somiljain7**
#192 
tox is not required anymore

### CODE REVIEW

**Comment by chinmayshah99** [comment]
We also need to remove it from github actions and add pytest there

**Comment by codeboy5** [comment]
> We also need to remove it from github actions and add pytest there

Hey @chinmayshah99 I had a doubt, pytest and tox are used for different things, I guess tox is just used to check whether out code works in different python versions as compared to pytest which is used for unit test. Is that correct ?

**Comment by chinmayshah99** [comment]
> Hey @chinmayshah99 I had a doubt, pytest and tox are used for different things, I guess tox is just used to check whether out code works in different python versions as compared to pytest which is used for unit test. Is that correct ?

Yeah they are different. But since we use different containers for different python versions, we no longer need tox. Because in each container, we have a different python version installed.

**Review by chinmayshah99 — CHANGES_REQUESTED** [review]
Can we remove tox tests from github actions too?

**Comment by somiljain7** [comment]
Hey @chinmayshah99 
I was unable to find deciding factor in setup .py
Can you assign someone else for this
Sorry  for disturbance

**Comment by alejandrosame** [comment]
I can take it from here, since it is also raising an error when following Docker instructions:

```
root@050b6b45660c:~/PyDP# make test-all
tox
make: tox: Command not found
make: *** [Makefile:67: test-all] Error 127
```

**Pull request closed without merging**
