### PR TITLE
Wrapper for numerical mechanism class [Continuation from #372]

### PR DESCRIPTION
**Pull request by levzlotnik**
## Description
This is continuation of the #372 Pull Request by @dnabanita7. It includes fixes for API and C++ implementation. 
- [x] Build Process
- [x] Dependencies
- [x] Python Bindings (C++ side)
- [x] Python Bindings (Python side)

## Affected Dependencies
[From #372] Added `bazel_skylib` for `com_google_protobuf` dependency.

## How has this been tested?
Testing WIP. Will test the python side.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by levzlotnik** [comment]
@chinmayshah99 Only Windows build is failing, can I continue with the implementation?

**Comment by chinmayshah99** [comment]
> @chinmayshah99 Only Windows build is failing, can I continue with the implementation?

There are changes in the WORKSPACE file that needs to be removed.

**Comment by levzlotnik** [comment]
> > @chinmayshah99 Only Windows build is failing, can I continue with the implementation?
> 
> There are changes in the WORKSPACE file that needs to be removed.

What changes?

**Comment by chinmayshah99** [comment]
> > > @chinmayshah99 Only Windows build is failing, can I continue with the implementation?
> > 
> > 
> > There are changes in the WORKSPACE file that needs to be removed.
> 
> What changes?

Last two changes. I don't think those are needed

**Comment by levzlotnik** [comment]
@chinmayshah99 I've fixed the dependencies, now build works.  
I see that there's `pydp/ml/mechanisms/` and they are essentially the same as the google-dp numerical mechanisms. Should I replace them with the ones we got from pybind11?

**Comment by chinmayshah99** [comment]
> I see that there's `pydp/ml/mechanisms/` and they are essentially the same as the google-dp numerical mechanisms. Should I replace them with the ones we got from pybind11?

There are some differences in the implementation of the ML part. This can be taken up as a separate PR post the discussion in the slack channel.

**Comment by chinmayshah99** [comment]
hi @levzlotnik, the windows py39 build is failing. Can you please take a look into it?

**Comment by levzlotnik** [comment]
Hey @chinmayshah99, could you please review this? imho it's ready

**Review by chinmayshah99 — APPROVED** [review]

**Pull request merged**
