### PR TITLE
Added README.md file to describe about Laplace

### PR DESCRIPTION
**Pull request by Rajatendu1**
This file contains the description for the laplace.ipynb file .

## Description
Added the description for the Laplace jupyter notebook
## Affected Dependencies
None
## How has this been tested?
Just added a text file, no testing required
## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

### CODE REVIEW

**Comment by chinmayshah99** [comment]
I'm sorry, but this readme needs to be rewritten.

**Review by 8bitmp3 — CHANGES_REQUESTED** [review]
Hi @Rajatendu1 PTAL at https://github.com/OpenMined/PyDP/issues/312#issuecomment-719643728 https://github.com/OpenMined/PyDP/issues/312#issuecomment-719644197  https://github.com/OpenMined/PyDP/issues/312#issuecomment-719651282 https://github.com/OpenMined/PyDP/issues/312#issuecomment-719683340

**Review by chinmayshah99 — CHANGES_REQUESTED** [review]
I'm sorry, but this readme needs to be rewritten.

**Comment by chinmayshah99** [comment]
Closing due to in-activity

**Pull request closed without merging**
