### PR TITLE
added the slack support link in the main Readme.md file

### PR DESCRIPTION
**Pull request by ramesht007**
## Description
Added support to the slack channel and also added the description for #lib_pydp channel and #code_dp_python for easy joining and contribution.

### CODE REVIEW

**Comment by chinmayshah99** [comment]
Hey @ramesht007 ,
Thank you for opening a PR!
This looks the duplicate of #186

**Comment by ramesht007** [comment]
Hey @chinmayshah99 ,
Thanks for response but I thought I worked on #187,
I am new can you please guide me if i have done something wrong.

Thanks

**Comment by chinmayshah99** [comment]
If you see the discussion on #187 , #186 already did reference it and said it has completed it- https://github.com/OpenMined/PyDP/issues/187#issuecomment-645354107. 

You can take up any other issues or maybe just ask on the slack channel what's available for grab?

**Comment by ramesht007** [comment]
thanks @chinmayshah99 for the insight

**Comment by chinmayshah99** [comment]
No issues!
Yet again thanks for the PR! See you in thr future PRs :)

**Pull request closed without merging**
